import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [blogs, setBlogs] = useState([]);
  useEffect(() => {
    fetch("http://Localhost:3000/api/getblog")
      .then((a) => {
        return a.json();
      })
      .then((parsed) => setBlogs(parsed));
  }, []);
  console.log(blogs, "Blogss");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1 style={{ fontSize: "60px" }}>⚔️Hunting Coder⚔️</h1>
          <p style={{ fontSize: "20px" }}>
            A Blog for Hunting Coder by Coder's📜
          </p>
        </div>
        <div className={styles.imagewrapper}>
          <Image
            className={styles.codingImg}
            src="/Coding.webp"
            alt="Coding Image"
            width={675}
            height={380}
            priority
          />
        </div>
        <div className="blog">
          <h1 style={{ fontSize: "43px" }}>Popular Blogs</h1>
          {blogs.map((item, index) => {
            return (
              <div className="blogItem" key={index}>
                <h3>{item.title}</h3>
                <Link href={`/blogpost/${item.slug}`}>
                  <p>{item.content.substr(0, 42)}.....</p>
                </Link>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
